/**
 * Multi-Provider Data Fetching System
 *
 * Supports Massive.com (Polygon.io) and Finnhub.io with intelligent fallback.
 */

import type { StockQuote, ChartPoint } from '../../types'

export type ProviderName = 'massive' | 'finnhub' | 'yahoo' | 'mock'

export interface ProviderConfig {
  name: ProviderName
  apiKey: string
  enabled: boolean
  priority: number // Lower number = higher priority
}

export interface QuoteResponse {
  quote: StockQuote
  timestamp: number // Unix ms when the quote was generated by the provider
  source: ProviderName
}

export interface ChartResponse {
  chart: ChartPoint[]
  source: ProviderName
}

export interface PreMarketResponse {
  preMarketHigh?: number
  preMarketLow?: number
  source: ProviderName
}

export interface ProviderCapabilities {
  supportsRealTimeQuotes: boolean
  supportsPreMarket: boolean
  supportsIntradayChart: boolean
  supportsDailyChart: boolean
  maxRequestsPerMinute: number
}

export interface Provider {
  name: ProviderName
  capabilities: ProviderCapabilities

  fetchQuote(symbol: string): Promise<QuoteResponse | null>
  fetchChart(symbol: string, interval: string, from: string, to: string): Promise<ChartResponse | null>
  fetchPreMarket(symbol: string, date: string): Promise<PreMarketResponse | null>
}
