import type { AnchorTier } from './types';

export const EXCHANGE_RATE = 3.0;
export const MIN_PROFIT = 100;
export const MAX_PROFIT = 2000;
export const DEFAULT_PROFIT = 400;
export const MAX_DAILY_LOSS = 300;
export const SCALE_OUT_THRESHOLD = 300;

export const usdToIls = (usd: number) => Math.round(usd * EXCHANGE_RATE);

export const anchorTiers: AnchorTier[] = [
  {
    id: 'tier-1',
    emoji: '🟢',
    title: 'הפינוק המשפחתי והשקט השבועי',
    rangeUSD: [200, 300],
    rangeILS: [600, 900],
    quote: 'על המסך יש כרגע קנייה מלאה לסופר או יום כיף שלם עם הבנות – למה לסכן את זה?',
    products: [
      {
        id: 'tier1-groceries',
        name: 'עגלת סופר שופעת לסוף שבוע',
        description: 'בשרים, מוצרי חלב, פירות, ירקות ונשנושים למשפחה.',
        priceUSD: 200,
        priceILS: 600,
        category: 'משפחה',
        imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=600',
      },
      {
        id: 'tier1-dinner',
        name: 'ארוחת ערב זוגית במסעדת שף מפנקת',
        description: 'ארוחה זוגית מלאה כולל יין מעולה וקינוחים.',
        priceUSD: 300,
        priceILS: 900,
        category: 'חוויה',
        imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600',
      },
      {
        id: 'tier1-school',
        name: 'ציוד חזרה לבית ספר ממותג',
        description: '2 תיקים איכותיים חדשים + קלמרים מלאים בכל הציוד.',
        priceUSD: 200,
        priceILS: 600,
        category: 'ילדים',
        imageUrl: 'https://images.unsplash.com/photo-1588072432836-e10032774350?w=600',
      },
      {
        id: 'tier1-toys',
        name: 'בית בובות / ערכת לגו ענקית לילדות',
        description: 'צעצוע איכותי ומפואר שיעשה שמחה ענקית בבית.',
        priceUSD: 250,
        priceILS: 750,
        category: 'ילדים',
        imageUrl: 'https://images.unsplash.com/photo-1585366119957-e9730b6d0f60?w=600',
      },
      {
        id: 'tier1-vaadbayit',
        name: 'תשלום ועד בית לחודש שלם',
        description: 'כיסוי מלא של דמי הבית לחודש הקרוב – שקט נפשי בלי לחשוב על זה.',
        priceUSD: 200,
        priceILS: 600,
        category: 'בית',
        imageUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600',
      },
      {
        id: 'tier1-hobby',
        name: 'חוג לילדים לחודש שלם',
        description: 'מימון חוג ריקוד, כדורגל או אומנות לילד/ה לחודש שלם, כולל ציוד.',
        priceUSD: 220,
        priceILS: 660,
        category: 'ילדים',
        imageUrl: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=600',
      },
      {
        id: 'tier1-bowling',
        name: 'ערב באולינג ופיצה למשפחה',
        description: 'כמה משחקים, נעלי באולינג ופיצה לכולם – ערב כיף בלי לחשוב על התקציב.',
        priceUSD: 230,
        priceILS: 690,
        category: 'חוויה',
        imageUrl: 'https://images.unsplash.com/photo-1615397349754-cfa2066a298e?w=600',
      },
      {
        id: 'tier1-books',
        name: 'מלאי ספרים חדש לכל המשפחה',
        description: '20-30 ספרים חדשים לילדים ולהורים, לספרייה הביתית.',
        priceUSD: 240,
        priceILS: 720,
        category: 'ילדים',
        imageUrl: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=600',
      },
      {
        id: 'tier1-donation',
        name: 'אריזות מזון לנזקקים לפני החג',
        description: 'תרומת סלי מזון מלאים למשפחות מעוטות יכולת.',
        priceUSD: 250,
        priceILS: 750,
        category: 'צדקה',
        imageUrl: 'https://images.unsplash.com/photo-1593113646773-028c64a8f1b8?w=600',
      },
      {
        id: 'tier1-soldiers',
        name: 'חיזוקים וציוד לחיילים בשטח',
        description: 'שקיות שטח, ציוד חם ומזון לחיילים – תודה קטנה שמגיעה למקום הנכון.',
        priceUSD: 260,
        priceILS: 780,
        category: 'צדקה',
        imageUrl: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=600',
      },
      {
        id: 'tier1-wolt',
        name: 'מנוי חודשי להזמנות וולט למשפחה',
        description: 'הזמנת אוכל פעם בשבוע לכל המשפחה, לחודש שלם, בלי לבשל.',
        priceUSD: 270,
        priceILS: 810,
        category: 'משפחה',
        imageUrl: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600',
      },
      {
        id: 'tier1-buyme',
        name: 'שובר BuyMe לבחירה חופשית',
        description: 'שובר לארוחה, חוויה או קניה – את/ה בוחר/ת מה עושים עם הרווח.',
        priceUSD: 280,
        priceILS: 840,
        category: 'מתנה',
        imageUrl: 'https://images.unsplash.com/photo-1607083206968-13611e3d76db?w=600',
      },
      {
        id: 'tier1-concert',
        name: 'כרטיסים להופעה מוזיקלית בארץ',
        description: 'יוצאים להופעה חיה של אמן אהוב – זיכרון שלא נמכר בברוקר.',
        priceUSD: 290,
        priceILS: 870,
        category: 'חוויה',
        imageUrl: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=600',
      },
      {
        id: 'tier1-mortgage-partial',
        name: 'כיסוי חלקי של תשלום המשכנתא',
        description: '900 ₪ מתוך 5,000 ₪ התשלום החודשי – כל טרייד מוריד עוד קצת מהעול.',
        priceUSD: 300,
        priceILS: 900,
        category: 'בית',
        imageUrl: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=600',
      },
      {
        id: 'tier1-fuel',
        name: 'מילוי מיכל דלק לרכב',
        description: 'תדלוק מלא לרכב המשפחתי – עוד נסיעה בלי לחשוב על התקציב.',
        priceUSD: 133,
        priceILS: 400,
        category: 'רכב',
        imageUrl: 'https://images.unsplash.com/photo-1487754180451-c456f719a1fc?w=600',
      },
      {
        id: 'tier1-electronics-insurance',
        name: 'ביטוח חודשי למכשירי חשמל חדשים',
        description: 'כיסוי חודשי לכל המכשירים החדשים בבית – שקט נפשי מתקלות.',
        priceUSD: 250,
        priceILS: 750,
        category: 'ביטוח',
        imageUrl: 'https://images.unsplash.com/photo-1550355291-bbee04a92027?w=600',
      },
      {
        id: 'tier1-internet',
        name: 'מנוי אינטרנט חודשי (סלקום)',
        description: 'תשלום חודשי לאינטרנט הביתי – כבר משולם, אין למה לחשוב.',
        priceUSD: 50,
        priceILS: 150,
        category: 'חשבונות',
        imageUrl: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=600',
      },
      {
        id: 'tier1-health-insurance',
        name: 'ביטוח בריאות חודשי',
        description: 'כיסוי ביטוח בריאות פרטי לחודש שלם למשפחה.',
        priceUSD: 83,
        priceILS: 250,
        category: 'ביטוח',
        imageUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=600',
      },
      {
        id: 'tier1-charity-monthly',
        name: 'תרומה חודשית לעמותת צדקה',
        description: 'תרומה קבועה לעמותה שתומכת בנזקקים ובחוסכים בארץ.',
        priceUSD: 120,
        priceILS: 360,
        category: 'צדקה',
        imageUrl: 'https://images.unsplash.com/photo-1593113646773-028c64a8f1b8?w=600',
      },
      {
        id: 'tier1-aliexpress',
        name: 'סשן קניות באלי אקספרס',
        description: 'כמה הזמנות קטנות שכבר מזמן מחכות בעגלה – בלי רגשות אשם.',
        priceUSD: 117,
        priceILS: 350,
        category: 'קניות',
        imageUrl: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=600',
      },
      {
        id: 'tier1-shein',
        name: 'מסע קניות בגדים לבנות מ-Shein',
        description: 'חידוש המלתחה לבנות בכמה פריטים חדשים ואופנתיים.',
        priceUSD: 167,
        priceILS: 500,
        category: 'ילדים',
        imageUrl: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=600',
      },
    ],
  },
  {
    id: 'tier-2',
    emoji: '🟢',
    title: 'מוצרי איכות ונוחות לבית',
    rangeUSD: [400, 500],
    rangeILS: [1200, 1500],
    quote: 'בטרייד הבודד הזה מימנת מכשיר חשמל חדש לבית או שדרוג מלתחה לכל הבנות.',
    products: [
      {
        id: 'tier2-grill',
        name: 'מכשיר Ninja Grill Max / טיגון באוויר חם',
        description: 'שדרוג קולינרי מהיר ובריא למטבח.',
        priceUSD: 400,
        priceILS: 1200,
        category: 'בית',
        imageUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600',
      },
      {
        id: 'tier2-wardrobe',
        name: 'שדרוג מלתחה מלאה ל-4 בנות',
        description: "מסע קניות של בגדים, פיג'מות ונעלי ספורט לעונה.",
        priceUSD: 450,
        priceILS: 1350,
        category: 'משפחה',
        imageUrl: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=600',
      },
      {
        id: 'tier2-vacuum',
        name: 'שואב-שוטף רצפות אלחוטי Dreame / Tineco',
        description: 'שקט בניקיון ותחזוקת הבית.',
        priceUSD: 500,
        priceILS: 1500,
        category: 'בית',
        imageUrl: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600',
      },
      {
        id: 'tier2-watch',
        name: 'שעון חכם Apple Watch SE / Galaxy Watch',
        description: 'מעקב בריאות, התראות וספורט.',
        priceUSD: 400,
        priceILS: 1200,
        category: 'טכנולוגיה',
        imageUrl: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600',
      },
      {
        id: 'tier2-mortgage',
        name: 'תשלום נכבד מהמשכנתא החודשית',
        description: '1,200 ₪ מתוך 5,000 ₪ החודשיים – כמעט רבע מהמשכנתא מכוסה בטרייד אחד.',
        priceUSD: 400,
        priceILS: 1200,
        category: 'בית',
        imageUrl: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=600',
      },
      {
        id: 'tier2-tuition',
        name: 'שכר לימוד חודשי לילדים',
        description: 'כיסוי שכר לימוד או צהרון לחודש שלם לשני ילדים.',
        priceUSD: 420,
        priceILS: 1260,
        category: 'ילדים',
        imageUrl: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=600',
      },
      {
        id: 'tier2-shabbatclothes',
        name: 'בגדי שבת חדשים לכל המשפחה',
        description: 'מלתחת שבת מחודשת – לך, לאישה ולבנות.',
        priceUSD: 440,
        priceILS: 1320,
        category: 'משפחה',
        imageUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=600',
      },
      {
        id: 'tier2-vouchers',
        name: 'שוברי קניה לרשתות אופנה וטכנולוגיה',
        description: 'שוברים גמישים למימוש בכל רשת – מתאים למי שקשה לרצות.',
        priceUSD: 450,
        priceILS: 1350,
        category: 'מתנה',
        imageUrl: 'https://images.unsplash.com/photo-1607082349566-187342175e2f?w=600',
      },
      {
        id: 'tier2-bbq-unit',
        name: 'ערב מנגל גדול למחלקה במילואים',
        description: 'בשרים, שתייה וציוד לערב שמחזק את החברים לנשק.',
        priceUSD: 460,
        priceILS: 1380,
        category: 'צדקה',
        imageUrl: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=600',
      },
      {
        id: 'tier2-zimmer',
        name: 'סוף שבוע בצימר יוקרתי בצפון',
        description: "לילה או שניים בצימר עם ג'קוזי – בריחה קטנה מהעיר.",
        priceUSD: 470,
        priceILS: 1410,
        category: 'חופשה',
        imageUrl: 'https://images.unsplash.com/photo-1499696010180-025ef6e1a8f9?w=600',
      },
      {
        id: 'tier2-renovation-small',
        name: 'שיפוץ קטן בבית',
        description: 'צביעת חדר, תיקוני אינסטלציה ושדרוג פינתי.',
        priceUSD: 480,
        priceILS: 1440,
        category: 'בית',
        imageUrl: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=600',
      },
      {
        id: 'tier2-batmitzvah',
        name: 'הפקדה לחיסכון לבת המצווה',
        description: 'עוד קצת קרוב לתקציב האירוע והמתנות לבת המצווה.',
        priceUSD: 485,
        priceILS: 1455,
        category: 'חיסכון',
        imageUrl: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=600',
      },
      {
        id: 'tier2-concert-abroad-partial',
        name: 'מקדמה לכרטיסי הופעה בחו"ל',
        description: 'התחלה של מימון נסיעה קצרה להופעה של האמן האהוב עליך.',
        priceUSD: 490,
        priceILS: 1470,
        category: 'חוויה',
        imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600',
      },
      {
        id: 'tier2-kidsroom',
        name: 'ריהוט חדש לחדרי הילדים',
        description: 'מיטות, שולחנות כתיבה וארונות חדשים לחדרי הבנות.',
        priceUSD: 500,
        priceILS: 1500,
        category: 'בית',
        imageUrl: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=600',
      },
      {
        id: 'tier2-car-insurance-mandatory',
        name: 'ביטוח חובה שנתי לרכב',
        description: 'כיסוי ביטוח החובה השנתי לרכב – שקט משפטי לכל השנה.',
        priceUSD: 577,
        priceILS: 1730,
        category: 'רכב',
        imageUrl: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?w=600',
      },
    ],
  },
  {
    id: 'tier-3',
    emoji: '🟢',
    title: 'חוויות, חופשות וטכנולוגיה',
    rangeUSD: [700, 1000],
    rangeILS: [2100, 3000],
    quote: 'זה לא עוד מספר על הצג – אלו כרטיסי טיסה זוגיים לחופשה בחו"ל או דייסון חדש!',
    products: [
      {
        id: 'tier3-flights',
        name: 'זוג כרטיסי טיסה הלוך-חזור לאירופה',
        description: 'חופשה זוגית ביוון, קפריסין, רומא או בודפשט.',
        priceUSD: 700,
        priceILS: 2100,
        category: 'חופשה',
        imageUrl: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=600',
      },
      {
        id: 'tier3-dyson',
        name: 'שואב אבק Dyson V12/V15 אלחוטי מתקדם',
        description: 'מכשיר הדגל לניקיון יסודי של כל הבית.',
        priceUSD: 900,
        priceILS: 2700,
        category: 'בית',
        imageUrl: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?w=600',
      },
      {
        id: 'tier3-boutique',
        name: 'סופ"ש זוגי במלון בוטיק / צימר יוקרתי',
        description: '2 לילות כולל ארוחות בוקר ופינוקי ספא.',
        priceUSD: 800,
        priceILS: 2400,
        category: 'חופשה',
        imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600',
      },
      {
        id: 'tier3-phone',
        name: 'סמארטפון דגל מתקדם Galaxy S24 / iPhone',
        description: 'מכשיר חזק לצילום, עבודה וביצועים.',
        priceUSD: 1000,
        priceILS: 3000,
        category: 'טכנולוגיה',
        imageUrl: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600',
      },
      {
        id: 'tier3-kitchen',
        name: 'שיפוץ מטבח חלקי',
        description: 'החלפת משטח עבודה, ברזים וארונות עליונים במטבח.',
        priceUSD: 700,
        priceILS: 2100,
        category: 'בית',
        imageUrl: 'https://images.unsplash.com/photo-1556912167-f556f1f39fdf?w=600',
      },
      {
        id: 'tier3-ski',
        name: 'חופשת סקי משפחתית בחו"ל',
        description: 'כמה ימים באלפים או בבולגריה – ציוד, סקי ומעלית כלולים.',
        priceUSD: 750,
        priceILS: 2250,
        category: 'חופשה',
        imageUrl: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=600',
      },
      {
        id: 'tier3-kids-yearly',
        name: 'שנה שלמה של חוגים לכל הילדים',
        description: 'מימון חוגים ופעילויות לכל הילדים לשנה שלמה.',
        priceUSD: 780,
        priceILS: 2340,
        category: 'ילדים',
        imageUrl: 'https://images.unsplash.com/photo-1607453998774-d533f65dac99?w=600',
      },
      {
        id: 'tier3-soldiers-big',
        name: 'ציוד חם וחורפי ליחידה שלמה',
        description: 'ביגוד תרמי, שקי שינה וציוד חורפי לכל היחידה.',
        priceUSD: 800,
        priceILS: 2400,
        category: 'צדקה',
        imageUrl: 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=600',
      },
      {
        id: 'tier3-amusement',
        name: 'יום כיף גדול בפארק שעשועים + לינה',
        description: 'כרטיסים לכל המשפחה, אוכל ולינה בבית מלון קרוב לפארק.',
        priceUSD: 850,
        priceILS: 2550,
        category: 'חוויה',
        imageUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600',
      },
      {
        id: 'tier3-concert-abroad',
        name: 'טיסה + כרטיסים להופעה בחו"ל',
        description: 'טסים לראות את האמן האהוב עליך בהופעה חיה בחו"ל.',
        priceUSD: 900,
        priceILS: 2700,
        category: 'חוויה',
        imageUrl: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=600',
      },
      {
        id: 'tier3-batmitzvah-big',
        name: 'הפקדה גדולה לחיסכון לבת המצווה',
        description: 'צעד משמעותי לקראת האירוע והמתנה לבת המצווה.',
        priceUSD: 920,
        priceILS: 2760,
        category: 'חיסכון',
        imageUrl: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=600',
      },
      {
        id: 'tier3-desert-camping',
        name: 'טיול קמפינג משפחתי במדבר',
        description: 'כמה לילות אוהלים, גיבוש משפחתי וסוף שבוע בטבע.',
        priceUSD: 950,
        priceILS: 2850,
        category: 'חופשה',
        imageUrl: 'https://images.unsplash.com/photo-1451337516015-6b6e9a44a8a3?w=600',
      },
      {
        id: 'tier3-donation-big',
        name: 'תרומה גדולה לארגון צדקה',
        description: 'סלי מזון וציוד למשפחות נזקקות בהיקף גדול.',
        priceUSD: 980,
        priceILS: 2940,
        category: 'צדקה',
        imageUrl: 'https://images.unsplash.com/photo-1615461066841-6116e61058f4?w=600',
      },
      {
        id: 'tier3-tuition-semester',
        name: 'שכר לימוד לסמסטר שלם',
        description: 'כיסוי שכר לימוד לקורס, חוג לימודי או תגבור לסמסטר שלם.',
        priceUSD: 1000,
        priceILS: 3000,
        category: 'ילדים',
        imageUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=600',
      },
      {
        id: 'tier3-property-tax-water',
        name: 'ארנונה ומים לחודשיים',
        description: 'תשלום דו-חודשי לארנונה ומים – חוב שנעלם ברגע אחד.',
        priceUSD: 833,
        priceILS: 2500,
        category: 'בית',
        imageUrl: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600',
      },
    ],
  },
  {
    id: 'tier-4',
    emoji: '🟢',
    title: 'מהפך בבית וחופשה משפחתית',
    rangeUSD: [1200, 1500],
    rangeILS: [3600, 4500],
    quote: 'מימוש של $1,500 זה מימון מלא של חופשה משפחתית שלמה או טלוויזיית ענק!',
    products: [
      {
        id: 'tier4-familyvacation',
        name: 'חופשת קיץ משפחתית מלאה ביעד קרוב',
        description: 'טיסות ומלון לכל המשפחה (6 נפשות).',
        priceUSD: 1500,
        priceILS: 4500,
        category: 'חופשה',
        imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600',
      },
      {
        id: 'tier4-tv',
        name: "מסך ענק 75-85 אינץ' 4K לסלון + מקרן קול",
        description: 'חוויית קולנוע ביתית מושלמת.',
        priceUSD: 1300,
        priceILS: 3900,
        category: 'בית',
        imageUrl: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=600',
      },
      {
        id: 'tier4-sofa',
        name: 'מערכת ישיבה פינתית מפנקת (ספה חדשה)',
        description: 'סלון משודרג מבד דוחה כתמים.',
        priceUSD: 1500,
        priceILS: 4500,
        category: 'בית',
        imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600',
      },
      {
        id: 'tier4-yearly',
        name: 'שקט שנתי: סגירת הוצאות פתיחת שנה וחוגים',
        description: 'שקט נפשי מלא לכל הבנות לשנה שלמה.',
        priceUSD: 1400,
        priceILS: 4200,
        category: 'משפחה',
        imageUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=600',
      },
      {
        id: 'tier4-mortgage-full',
        name: 'כיסוי מלא (בקירוב) של המשכנתא החודשית',
        description: 'התשלום החודשי כולו כבר מכוסה – חודש שלם בלי לחשוב על זה.',
        priceUSD: 1500,
        priceILS: 4500,
        category: 'בית',
        imageUrl: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=600',
      },
      {
        id: 'tier4-wedding-fund',
        name: 'הפקדה לקרן החתונה של הבנות',
        description: 'עוד צעד גדול לקראת יום החתונה של אחת הבנות.',
        priceUSD: 1450,
        priceILS: 4350,
        category: 'חיסכון',
        imageUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=600',
      },
      {
        id: 'tier4-renovation-big',
        name: 'שיפוץ מלא של חדר או מרחב בבית',
        description: 'שיפוץ יסודי – ריצוף, צבע וריהוט לחדר שלם.',
        priceUSD: 1400,
        priceILS: 4200,
        category: 'בית',
        imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600',
      },
      {
        id: 'tier4-vacation-abroad-family',
        name: 'חופשה משפחתית ארוכה בחו"ל',
        description: 'שבוע שלם לכל המשפחה – טיסות, מלון וחופש מהראש.',
        priceUSD: 1350,
        priceILS: 4050,
        category: 'חופשה',
        imageUrl: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=600',
      },
      {
        id: 'tier4-batmitzvah-full',
        name: 'מימון מלא של אירוע בת המצווה',
        description: 'אולם, קייטרינג ועיצוב – האירוע כולו מכוסה.',
        priceUSD: 1300,
        priceILS: 3900,
        category: 'משפחה',
        imageUrl: 'https://images.unsplash.com/photo-1560785496-3c9d27877182?w=600',
      },
      {
        id: 'tier4-tuition-year',
        name: 'שכר לימוד לשנה שלמה',
        description: 'כיסוי שכר לימוד מלא לילד/ה לשנת לימודים שלמה.',
        priceUSD: 1250,
        priceILS: 3750,
        category: 'ילדים',
        imageUrl: 'https://images.unsplash.com/photo-1571260899304-425eee4c7efc?w=600',
      },
      {
        id: 'tier4-soldiers-huge',
        name: 'תרומה משמעותית לתמיכה בחיילי מילואים',
        description: 'תרומה גדולה לארגון שתומך במשפחות חיילי מילואים.',
        priceUSD: 1200,
        priceILS: 3600,
        category: 'צדקה',
        imageUrl: 'https://images.unsplash.com/photo-1591604021695-0c69b7c05981?w=600',
      },
      {
        id: 'tier4-vouchers-big',
        name: 'שוברי קניה גדולים לכל המשפחה',
        description: 'שוברים לטכנולוגיה, אופנה וחוויות לכל בני הבית.',
        priceUSD: 1220,
        priceILS: 3660,
        category: 'מתנה',
        imageUrl: 'https://images.unsplash.com/photo-1607083206968-13611e3d76db?w=600',
      },
      {
        id: 'tier4-piggybank-mega',
        name: 'כרית ביטחון משפחתית גדולה',
        description: 'תוספת נכבדה לחיסכון המשפחתי לימים גשומים.',
        priceUSD: 1480,
        priceILS: 4440,
        category: 'חיסכון',
        imageUrl: 'https://images.unsplash.com/photo-1579621970795-87facc2f976d?w=600',
      },
      {
        id: 'tier4-ski-family',
        name: 'חופשת סקי משפחתית מלאה באירופה',
        description: 'כל המשפחה באלפים – טיסות, סקי-פס וציוד לכולם.',
        priceUSD: 1500,
        priceILS: 4500,
        category: 'חופשה',
        imageUrl: 'https://images.unsplash.com/photo-1548777123-e216912df7d8?w=600',
      },
      {
        id: 'tier4-car-insurance-comprehensive',
        name: 'ביטוח מקיף שנתי לרכב',
        description: 'כיסוי ביטוח מקיף מלא לרכב לשנה שלמה – גם לתאונות, גם לגניבה.',
        priceUSD: 1333,
        priceILS: 4000,
        category: 'רכב',
        imageUrl: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=600',
      },
    ],
  },
];
